apiVersion: v1
kind: Service
metadata:
  name: mlops-assignment-service
spec:
  type: LoadBalancer 
  selector:
    app: mlops-assignment-app
  ports:
  - protocol: TCP
    port: 80      
    targetPort: 8000 
    
