# Use Python 3.12 slim image 
FROM python:3.12-slim 

# Set working directory 
WORKDIR /app 

# Copy requirements first for better caching
COPY deployment/requirements.txt

# Install Python dependencies 
RUN pip install --no-cache-dir -r requirements.txt 

# Copy the model artifacts
COPY artifacts ./artifacts

# Copy the application code
COPY deployment/ .

# Expose the port FASTAPI will run on
EXPOSE 8000

#6. Command to run the FASTAPI application
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"] 