# .github/workflows/ci.yml
name: CI Pipeline with Model testing

on:
  pull_request:
    branches: [ main ]

jobs:
  test-and-report:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pull-requests: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
     
    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Install dependencies   
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up DVC
      run: |
        dvc pull artifacts/model.joblib

    - name: Run tests
      run: |
        python3 test.py 2>&1 > test_output.txt
  
    - name: Setup CML
      uses: iterative/setup-cml@v2

    - name: Create CML Report
      env: 
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "test output" > report.md
        echo "\`\`\`" >> report.md
        cat test_output.txt >> report.md
        echo "\`\`\`" >> report.md
        cml comment create report.md
